version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:v1.36.1-focal
    parallelism: 4
    working_directory: ~/app

    steps:
      - checkout
      - run: npm i -D @playwright/test
      - run: npx playwright install chrome
      - run:
          name: run the test.
          command: |
            set -x
            TOTAL_SHARDS=4
            CURRENT_SHARD=$((CIRCLE_NODE_INDEX + 1))
            npx playwright test --project=chromium --reporter=line,allure-playwright --shard=$CURRENT_SHARD/$TOTAL_SHARDS || true
            set +x
            # The build will fail if the tests fail

      - run:
          name: download allurectl
          command: |
            wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -O ./allurectl
            chmod +x ./allurectl
            ls -al allurectl

      - run:
          name: upload to testsops allure results
          command: |
            export ALLURE_ENDPOINT=https://amielmelio.testops.cloud/
            export ALLURE_TOKEN=53136322-abb9-45c8-b849-23b5275fe82d
            export ALLURE_PROJECT_ID=1
            export ALLURE_LAUNCH_NAME="playwright tests e2e"
            export ALLURE_LAUNCH_TAGS="release, critical"
            # Run upload process somewhere
            ./allurectl upload ./allure-results

workflows:
  build:
    jobs:
      - build
